name: LaTeX PDF Build

on:
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install TeX + Make
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full make

      - name: Build PDF (ignore latexmk errors)
        run: make || true

      - name: Move output PDF
        run: |
          mkdir out
          cp build/main.pdf out/aw4null.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-PDF
          path: out/aw4null.pdf
