name: LaTeX Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full make

      - name: Build PDF using Makefile
        run: make  # or `make all` or a specific target like `make paper.pdf` if defined

      - name: Find PDF artifact
        run: |
          find . -type f -name "*.pdf"
        # Just for debugging — optional, remove if not needed

      - name: Rename PDF for release
        run: |
          mkdir output
          cp build/*.pdf output/paper.pdf  # adjust path if PDF lands elsewhere

      - name: Create GitHub Release and upload PDF
        uses: softprops/action-gh-release@v2
        with:
          files: output/paper.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
