name: Build and Release PDF

on:
  push:
    tags:
      - 'v*'  # Only run when tags starting with "v" are pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Makefile (alternative to above if using Make)
        run: make

      - name: Upload PDF to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
